#!/bin/sh
# Copyright (c) 2011 Ryan Souza
# Send the commit has to publictimestamp.org for
# notarization.

TIMESTAMP_SCRIPT="git-notarize"
HASH="`git rev-parse HEAD`"
TIMESTAMP_FILE=/tmp/git-notarize-"$HASH"
trap "rm -f $TIMESTAMP_FILE" 0 1 2 3 15
echo "$HASH" > $TIMESTAMP_FILE
$TIMESTAMP_SCRIPT send $TIMESTAMP_FILE
